version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - db
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
